name: Deploy to Garlic
on: 
  workflow_dispatch:
  push:
    branches: [master,main]
    paths-ignore:
      - '**.yml'
      - '!.github/workflows/deploygarlic.yml'
      - '**.md'
      - '.gitignore'

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    - name: Trigger Deployment
      env:
        LC_github_key: ${{ secrets.GARLIC_TOKEN }}    
      run: ssh -o "SendEnv LC_github_key" graic@${{ secrets.SSH_HOST }} ~/kesto/ci.sh




